[package]
name = "warp-rest-api-service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "warp-rest-api-service"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
tokio = { version = "1.49.0", features = ["full"] }
warp = { version = "0.4.2", features = ["server"] }
